### ISSUE TITLE
not working for some langs

### ISSUE THREAD

**Issue by namiwang** [pd4d10/highlight#1]
I'm playing with the web demo and some languages are not working.

![Screen Shot 2019-09-11 at 20 42 01](https://user-images.githubusercontent.com/1160688/64698037-afda8600-d4d4-11e9-9d0c-b7a963789f0b.png)
![Screen Shot 2019-09-11 at 20 42 16](https://user-images.githubusercontent.com/1160688/64698038-b0731c80-d4d4-11e9-81bd-bdd5193e05f1.png)

**Comment by pd4d10** [comment]
It is a bug of gallery and already been fixed in the latest deploy: https://pd4d10.github.io/highlight/

Thanks for your report!

BTW, seems there is a little problem with font family (monospace not working) at Flutter web. https://github.com/flutter/flutter/issues/38972#issuecomment-533499402
