### ISSUE TITLE
Is it possible to set highlight block to full width?

### ISSUE THREAD

**Issue by yeszao** [pd4d10/highlight#4]
Hello,

I use these plugin in my app, it's great!
This is the preview image:

![WechatIMG6](https://user-images.githubusercontent.com/3072379/67392780-bda32100-f5d3-11e9-94bd-4906666dc60b.jpeg)

So I'd like to know if I can set the code block as full width?

Thanks!

**Comment by pd4d10** [comment]
```dart
Row(
  children: <Widget>[
    Expanded(
      child: HighlightView(code)
    ),
  ],
)
```

Does this suit your needs?

**Comment by yeszao** [comment]
Yes, It works.
Thank you very much!
