### ISSUE TITLE
List<String> will be trimed in <pre>

### ISSUE THREAD

**Issue by yeszao** [pd4d10/highlight#5]
Hi,

I had a same Java code wrapped with `<pre>` tag, like this:
```java
List<Integer> arr = new List<Integer>;
```
when I display it in flutter with **highlight**, it will be trimed to:
```java
List arr = new List;
```
Is there a method to resovle it?
Thanks!

**Comment by pd4d10** [comment]
Could you please provide the full code?

**Comment by yeszao** [comment]
Sorry, I debug the code again, the problem was cause by other plugin: flutter_html, it treated `<Integer>`  as a html block.
